steps:
  # Build and push images using Docker Compose
  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', '-f', 'docker-compose.yaml', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', '-f', 'docker-compose.yaml', 'push']
