steps:
  # Build frontend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', 'build', 'frontend']

  # Build backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['compose', 'build', 'backend']

  # Push the built images to Google Container Registry (GCR)
  - name: 'gcr.io/final-project/jobmatch'
    args: ['compose', 'push']

  # Deploy the Docker Compose application
  - name: 'gcr.io/inal-project/jobmatch'
    args: ['-f', 'docker-compose.yaml', 'up', '-d']
