steps:
  # Build frontend service
  - name: 'gcr.io/final-project-421420/jobmatch-frontend'
    args: ['compose', 'build', 'frontend']

  # Build backend service
  - name: 'gcr.io/final-project-421420/jobmatch-backend'
    args: ['compose', 'build', 'backend']

  # Push the built images to Google Container Registry (GCR) for frontend service
  - name: 'gcr.io/final-project-421420/jobmatch-frontend'
    args: ['compose', 'push']

  # Push the built images to Google Container Registry (GCR) for backend service
  - name: 'gcr.io/final-project-421420/jobmatch-backend'
    args: ['compose', 'push']
